### ISSUE TITLE
Get Visibilities with the V4

### ISSUE THREAD

**Issue by jdrevon** [ivezic/dusty#3]
Hello,

 I used the V4 of DUSTY and by looking at the V4 manual I saw that the Visibilities, which have been incorporated in the V2 updated manual from 2017 version, is no longer available. I would have liked to know if it's something which is normal or not. And if it is, is it planned to incorporate this option again?

Thx in advance
Regards 

Julien

**Comment by ivezic** [comment]
Hi Julien,
unfortunately, we didn't have resources to complete the full port of utilities from V2 to V4. If you are using V4 and need visibilities, your best option is to write a little wrapper around the relevant subroutines from V2 and post-process image files produced with V4. The main subroutine is 
SUBROUTINE Visibili(IntOut)  and you can find it (and supporting subroutines) in V2 dusty.f
Please let us know if you decide to do so and run into difficulties. Alternatively, you can implement this relatively simply integration with Bessel functions in any other language (e.g. python).

**Comment by jdrevon** [comment]
> ```
>  Hi Julien,
> ```
> 
> unfortunately, we didn't have resources to complete the full port of utilities from V2 to V4. If you are using V4 and need visibilities, your best option is to write a little wrapper around the relevant subroutines from V2 and post-process image files produced with V4. The main subroutine is
> SUBROUTINE Visibili(IntOut) and you can find it (and supporting subroutines) in V2 dusty.f
> Please let us know if you decide to do so and run into difficulties. Alternatively, you can implement this relatively simply integration with Bessel functions in any other language (e.g. python).

Hi :)

 This is something that i just finished yesterday ;)  I used the Henkel Transform and compared results with the v2 until reaching a sufficient convergence. I wrote a quick Python code to make an estimation of the visibility with the output intensities in Jy.arsec^-2 gave by DUSTY v4. 

Thank you for your answers 

Julien
